# Generated by Django 5.2.16 on 2026-07-26 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('default_teacher_weekly_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('default_max_reduced_students', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('site_transition_slots', models.PositiveSmallIntegerField(default=1)),
                ('max_weight_morning', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_weight_afternoon', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_weight_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_weight_week', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('teacher', 'Teacher'), ('class', 'Class'), ('class_part', 'Class Part'), ('room', 'Room'), ('staff', 'Staff'), ('material', 'Material')], editable=False, max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('simultaneous_capacity', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domain.resource')),
            ],
            bases=('domain.resource',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domain.resource')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            bases=('domain.resource',),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domain.resource')),
                ('role', models.CharField(blank=True, max_length=50)),
            ],
            bases=('domain.resource',),
        ),
        migrations.AddField(
            model_name='resource',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='domain.site'),
        ),
    ]
