# Generated by Django 5.2.16 on 2026-07-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('competition_classes', models.ManyToManyField(blank=True, to='domain.competitionclass')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('max_reduced_students', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('didactic_weight', models.PositiveSmallIntegerField(default=1)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_minutes', models.PositiveIntegerField()),
                ('reduced_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('split_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='domain.studyplan')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('study_plan', 'subject'), name='uniq_service_plan_subject')],
            },
        ),
    ]
