# Generated by Django 5.2.16 on 2026-07-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_competitionclass_studyplan_discipline_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassPart',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domain.resource')),
                ('study_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='domain.studyplan')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='domain.classpartition')),
            ],
            bases=('domain.resource',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parts', models.ManyToManyField(related_name='groups', to='domain.classpart')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domain.resource')),
                ('year', models.PositiveSmallIntegerField()),
                ('max_weekly_weight_per_student', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preferred_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='domain.room')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='domain.studyplan')),
            ],
            bases=('domain.resource',),
        ),
        migrations.AddField(
            model_name='classpartition',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partitions', to='domain.schoolclass'),
        ),
        migrations.AddConstraint(
            model_name='classpartition',
            constraint=models.UniqueConstraint(fields=('school_class', 'name'), name='uniq_partition_per_class'),
        ),
    ]
