# Generated by Django 5.2.16 on 2026-07-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_classpartition_classpart_group_schoolclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='domain.resource')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('weekly_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('max_overtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='domain.subject')),
                ('teachable_subjects', models.ManyToManyField(blank=True, related_name='teachable_by', to='domain.subject')),
            ],
            bases=('domain.resource',),
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_minutes', models.PositiveIntegerField()),
                ('class_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.classpart')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.group')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='domain.teacher')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('class_part__isnull', True), ('group__isnull', True), ('school_class__isnull', False)), models.Q(('class_part__isnull', False), ('group__isnull', True), ('school_class__isnull', True)), models.Q(('class_part__isnull', True), ('group__isnull', False), ('school_class__isnull', True)), _connector='OR'), name='assignment_exactly_one_unit')],
            },
        ),
    ]
