# Generated by Django 5.2.16 on 2026-07-26 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_teacher_teachingassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('first_week_monday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_per_cycle', models.PositiveSmallIntegerField(default=5)),
                ('slots_per_day', models.PositiveSmallIntegerField(default=6)),
                ('slot_minutes', models.PositiveSmallIntegerField(default=60)),
                ('morning_end_slot', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='domain.period')),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='domain.schoolyear'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='domain.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_slot', models.PositiveSmallIntegerField()),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='domain.timegrid')),
            ],
        ),
    ]
