# Generated by Django 5.2.16 on 2026-07-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_period_schoolyear_timegrid_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_slots', models.PositiveSmallIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('alignment_ident', models.CharField(blank=True, max_length=50)),
                ('week_mask', models.PositiveBigIntegerField()),
                ('respects_breaks', models.BooleanField(default=False)),
                ('priority', models.BooleanField(default=False)),
                ('immobility', models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed'), ('locked_in_place', 'Locked In Place'), ('not_suspendable', 'Not Suspendable'), ('suspended', 'Suspended')], default='none', max_length=20)),
                ('classes', models.ManyToManyField(blank=True, related_name='activities', to='domain.schoolclass')),
                ('groups', models.ManyToManyField(blank=True, related_name='activities', to='domain.group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='domain.activity')),
                ('parts', models.ManyToManyField(blank=True, related_name='activities', to='domain.classpart')),
                ('rooms', models.ManyToManyField(blank=True, related_name='activities', to='domain.room')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='domain.site')),
                ('staff', models.ManyToManyField(blank=True, related_name='activities', to='domain.staffmember')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.subject')),
                ('teachers', models.ManyToManyField(blank=True, related_name='activities', to='domain.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='domain.activity')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.material')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='activities', through='domain.ActivityMaterialRequirement', to='domain.material'),
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('start_slot', models.PositiveSmallIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='domain.activity')),
                ('assigned_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.room')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='domain.schedule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule', 'activity'), name='uniq_placement_per_schedule')],
            },
        ),
    ]
