# Generated by Django 5.2.16 on 2026-07-26 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_activity_activitymaterialrequirement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('activities', models.ManyToManyField(blank=True, related_name='extractions', to='domain.activity')),
            ],
        ),
        migrations.CreateModel(
            name='RelaxationQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('max_presence', 'Max Presence'), ('free_guaranteed', 'Free Guaranteed'), ('half_days', 'Half Days'), ('subject_constraint', 'Subject Constraint'), ('sites', 'Sites'), ('breaks', 'Breaks'), ('optional_unavailability', 'Optional Unavailability'), ('unavailability', 'Unavailability'), ('max_hours', 'Max Hours'), ('didactic_weight', 'Didactic Weight')], max_length=30)),
                ('max_violations', models.PositiveSmallIntegerField()),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relaxation_quotas', to='domain.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceTimeConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('min_distribution', 'Min Distribution'), ('max_hours', 'Max Hours'), ('max_presence', 'Max Presence'), ('arrival_departure', 'Arrival Departure'), ('free_guaranteed', 'Free Guaranteed'), ('max_half_days', 'Max Half Days'), ('max_site_changes', 'Max Site Changes'), ('max_gap_hours', 'Max Gap Hours')], max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_constraints', to='domain.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('slot', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('hard', 'Hard'), ('optional', 'Optional'), ('preference', 'Preference')], max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='domain.resource')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('same_half_day_incompatible', 'Same Half Day Incompatible'), ('same_day_incompatible', 'Same Day Incompatible'), ('two_days_incompatible', 'Two Days Incompatible'), ('forbidden_sequence', 'Forbidden Sequence'), ('max_hours_half_day', 'Max Hours Half Day'), ('max_hours_day', 'Max Hours Day'), ('weekly_order', 'Weekly Order'), ('imposed_succession', 'Imposed Succession'), ('half_day_gap', 'Half Day Gap'), ('parts_before_class', 'Parts Before Class'), ('parts_after_class', 'Parts After Class'), ('parts_before_or_after_class_h', 'Parts Before Or After Class H'), ('parts_before_or_after_class_ab', 'Parts Before Or After Class Ab')], max_length=40)),
                ('param', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('class_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.classpart')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.group')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.schoolclass')),
                ('subject_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints_as_a', to='domain.subject')),
                ('subject_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints_as_b', to='domain.subject')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('class_part__isnull', True), ('group__isnull', True), ('school_class__isnull', False)), models.Q(('class_part__isnull', False), ('group__isnull', True), ('school_class__isnull', True)), models.Q(('class_part__isnull', True), ('group__isnull', False), ('school_class__isnull', True)), _connector='OR'), name='subject_constraint_one_unit')],
            },
        ),
    ]
