# Generated by Django 5.2.17 on 2026-08-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0007_extraction_relaxationquota_resourcetimeconstraint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutesettings",
            name="max_relaxed_constraints_per_resource",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relaxationquota",
            name="params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="relaxationquota",
            name="family",
            field=models.CharField(
                choices=[
                    ("max_presence", "Max Presence"),
                    ("free_guaranteed", "Free Guaranteed"),
                    ("half_days", "Half Days"),
                    ("subject_constraint", "Subject Constraint"),
                    ("sites", "Sites"),
                    ("breaks", "Breaks"),
                    ("optional_unavailability", "Optional Unavailability"),
                    ("unavailability", "Unavailability"),
                    ("max_hours", "Max Hours"),
                    ("didactic_weight", "Didactic Weight"),
                    ("arrival_departure", "Arrival Departure"),
                ],
                max_length=30,
            ),
        ),
    ]
