# Generated by Django 5.2.17 on 2026-08-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_alter_relaxationquota_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gaps', 'Gaps'), ('free_half_days', 'Free Half Days'), ('isolated', 'Isolated'), ('regularity', 'Regularity'), ('preferences', 'Preferences')], max_length=20)),
                ('population', models.CharField(choices=[('all', 'All'), ('teachers', 'Teachers'), ('classes', 'Classes')], default='all', max_length=10)),
                ('rank', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['rank', 'kind'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'population'), name='quality_criterion_unico')],
            },
        ),
    ]
