# Generated by Django 5.2.17 on 2026-08-28 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0010_qualitycriterion"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlotLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "grid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_labels",
                        to="domain.timegrid",
                    ),
                ),
            ],
            options={
                "ordering": ["slot"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("grid", "slot"), name="uniq_slot_label_per_grid"
                    )
                ],
            },
        ),
    ]
