# Generated by Django 5.2.17 on 2026-08-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_slotlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='election_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
