# Generated by Django 5.2.17 on 2026-08-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0012_service_election_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutesettings",
            name="gaps_split_at_lunch_classes",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="institutesettings",
            name="gaps_split_at_lunch_teachers",
            field=models.BooleanField(default=True),
        ),
    ]
