# Generated by Django 5.2.17 on 2026-08-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0013_institutesettings_gaps_split_at_lunch_classes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classpart",
            name="expected_students",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="placement",
            name="room_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="expected_students",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
