# Generated by Django 5.2.17 on 2026-08-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0014_classpart_expected_students_placement_room_locked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualitycriterion",
            name="kind",
            field=models.CharField(
                choices=[
                    ("gaps", "Gaps"),
                    ("free_half_days", "Free Half Days"),
                    ("isolated", "Isolated"),
                    ("regularity", "Regularity"),
                    ("preferences", "Preferences"),
                    ("weekly_spread", "Weekly Spread"),
                    ("slot_spread", "Slot Spread"),
                ],
                max_length=20,
            ),
        ),
    ]
