# Generated by Django 5.2.17 on 2026-08-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0015_alter_qualitycriterion_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="elective",
            field=models.BooleanField(default=False),
        ),
    ]
