# Generated by Django 5.2.17 on 2026-08-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0016_service_elective"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutesettings",
            name="free_day_exempt_mask",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
