# Generated by Django 5.2.17 on 2026-08-31 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0017_institutesettings_free_day_exempt_mask"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="substitutes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substituted_by",
                to="domain.activity",
            ),
        ),
    ]
