# Generated by Django 5.2.17 on 2026-08-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0018_activity_substitutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetupQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
            ],
        ),
    ]
